#image: node:latest
image: docker:latest
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE: zkissane/bridge_scorecard_api:latest
  CONTAINER: bridge_scorecard_api_ci_tests

services:
- name: docker:dind
  command: ["--tls=false"]


before_script:
  - docker info

  
stages:
  - build
  - run

# Job's name
first-job:
  # Define stage
  stage: build
  # What to run on the job.
  script:
    - docker build -t $IMAGE . 

second-job:
  stage: run
  script:
    - docker create $IMAGE -it --name $CONTAINER
    - docker exec -it npm test
    - docker stop $CONTAINER

second-job-parallel:
  stage: run
  script:
    - echo "I'm running at the same time as second-job!!!"