#image: node:latest
image: docker:20
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE: zkissane/bridge_scorecard_api
  CONTAINER: bridge_scorecard_api_ci_tests
  CONTAINER_TEST_IMAGE: $IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $IMAGE:latest

services:
- name: docker:dind
  command: ["--tls=false"]

stages:
  - build
  - test
  - release
  - deploy


before_script:
  - docker info

build:
  stage: build
  script:
    - 'echo "Building image: $CONTAINER_TEST_IMAGE"'
    - docker build -t $CONTAINER_TEST_IMAGE .
#    - docker push $CONTAINER_TEST_IMAGE

#test:
#  stage: test
#  script:
#    - 'echo "Pulling $CONTAINER_TEST_IMAGE to test using npm test"'
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker run $CONTAINER_TEST_IMAGE npm test    

# second-job:
#   stage: run
#   script:
#     - docker create $IMAGE -it --name $CONTAINER
#     - docker exec -it npm test
#     - docker stop $CONTAINER
