#image: node:latest
image: docker:20
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  REGISTRY: registry.local.zkissane.com
  IMAGE: zachistan/bridge_scorecard_api

  CURRENT_TAG: $REGISTRY/$IMAGE:$CI_COMMIT_REF_SLUG
  RELEASE_TAG: $REGISTRY/$IMAGE:latest

services:
- name: docker:dind
  command: ["--tls=false"]

stages:
  - build
  - test
  - release
  - deploy


before_script:
  - docker info

build:
  stage: build
  script:
    - 'echo "Building image: $CURRENT_TAG"'
    - docker buildx create --use
    - docker buildx build --platform linux/arm/v8,linux/amd64 --tag $CURRENT_TAG

test:
  stage: test
  script:
    - 'echo "Pulling $CURRENT_TAG to test using npm test"'
    - docker pull $CURRENT_TAG
    - docker run $CURRENT_TAG npm test    

# second-job:
#   stage: run
#   script:
#     - docker create $IMAGE -it --name $CONTAINER
#     - docker exec -it npm test
#     - docker stop $CONTAINER
